# Generated by Django 4.2.11 on 2026-05-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('travel_time', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=50)),
                ('ports', models.CharField(max_length=50)),
                ('hours', models.CharField(default='Open 24/7', max_length=100)),
                ('network', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('reliability', models.CharField(max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('connectors', models.JSONField(default=list)),
            ],
        ),
    ]
