# Generated by Django 6.0.3 on 2026-05-14 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_communityalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='cs_speed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
