# Generated by Django 6.0.3 on 2026-05-17 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chargingstation_cs_speed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EVVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('segment', models.CharField(max_length=50)),
                ('battery_capacity_kwh', models.FloatField(blank=True, null=True)),
                ('usable_capacity_kwh', models.FloatField(blank=True, null=True)),
                ('range_wltp_km', models.IntegerField(blank=True, null=True)),
                ('ac_max_power_kw', models.FloatField(blank=True, null=True)),
                ('ac_connector_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_phases', models.IntegerField(blank=True, null=True)),
                ('dc_max_power_kw', models.FloatField(blank=True, null=True)),
                ('dc_connector_type', models.CharField(blank=True, max_length=50, null=True)),
                ('km_per_hour_ac', models.IntegerField(blank=True, null=True)),
                ('km_per_hour_dc', models.IntegerField(blank=True, null=True)),
                ('full_charge_time_ac_hours', models.FloatField(blank=True, null=True)),
                ('full_charge_time_dc_minutes', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ev_images/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.evvehicle')),
            ],
        ),
    ]
