# Generated by Django 6.0.3 on 2026-05-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_points_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='flags',
            field=models.IntegerField(default=0),
        ),
    ]
