# Generated by Django 6.0.3 on 2026-05-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chargingstation_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='station_images/'),
        ),
    ]
