# Generated by Django 6.0.3 on 2026-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_chargingstation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='busy_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
