# Generated by Django 6.0.3 on 2026-05-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_chargingstation_busy_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_soc',
            field=models.IntegerField(default=65),
        ),
    ]
