services:
  - type: web
    name: smartlocator
    env: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate --settings=core.settings.production && python manage.py import_geojson --settings=core.settings.production && python manage.py import_ev_json --settings=core.settings.production && python manage.py collectstatic --settings=core.settings.production --noinput
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings.production
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ALLOWED_HOSTS
        value: smartlocator.onrender.com,localhost,127.0.0.1
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: GRAPHHOPPER_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET_NAME
        sync: false
      - key: R2_ENDPOINT_URL
        sync: false
